apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: kallithea
  name: kallithea-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kallithea
    spec:
      containers:
      - image: toras9000/docker-kallithea
        name: kallithea
        ports:
        - name: kallithea
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: kallithea
  name: kallithea
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: kallithea
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: kallithea
  name: kallithea-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kallithea
    spec:
      containers:
      - image: kallithea
        name: kallithea
        ports:
        - name: kallithea
          containerPort: 16868
          hostPort: 16868
        volumeMounts:
        - name: kallithea-storage
          mountPath: /data/db
      volumes:
      - name: kallithea-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: kallithea
  name: kallithea
spec:
  type: ClusterIP
  ports:
    - port: 16868
      targetPort: 16868
  selector:
    name: kallithea
